---
  - name: EXTRA REPOS - enable EPEL repository
    yum:
      name: epel-release
      state: installed
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
    register: epel_result
    until: epel_result is success
    retries: 3
    delay: 5

  - name: EXTRA REPOS - enable Remi's repository for CeontOS 7
    yum:
      name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
      state: installed
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
    register: remi_result
    until: remi_result is success
    retries: 3
    delay: 5

  - name: EXTRA REPOS - disable remi-safe repository
    command: yum-config-manager --disable remi-safe
    when: remi_result.changed

  - name: EXTRA REPOS - enable Remi's RPM repository
    command: yum-config-manager --enable remi-php72
    when: remi_result.changed

#  - debug:
#      var: remi_result

#  - debug:
#      var: hostvars